---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-scc-wp-agent
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: f76f2ed3-eb98-4e3d-b147-360485fd8a36
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-slz-roks-and-scc-wp-instances.sh"
        post_validation: "tests/scripts/post-validation-destroy-slz-roks-and-scc-wp-instances.sh"
