---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-scc-wp-agent
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 9423f9bc-1290-4c71-a9ac-01898bfa7ccc
    variations:
      - name: standard
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-slz-roks-and-scc-wp-instances.sh"
        post_validation: "tests/scripts/post-validation-destroy-slz-roks-and-scc-wp-instances.sh"
